//------------------------------------------------------------------------------
// <auto-generated>
//     �o�ӵ{���X�O�ѽd�����͡C
//
//     ��o���ɮ׶i�����ܧ�i��ɭP�z�����ε{�����ͥ��w�����欰�C
//     �p�G���s���͵{���X�A�N�|�мg��o���ɮת�����ܧ�C
// </auto-generated>
//------------------------------------------------------------------------------

namespace XxxFitnessCLub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string CommentContent { get; set; }
        public int MemberID { get; set; }
        public System.DateTime AddDate { get; set; }
        public bool IsApproved { get; set; }
        public Nullable<int> MealOptionID { get; set; }
        public int Rating { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string Feedback { get; set; }
    
        public virtual CommentCategory CommentCategory { get; set; }
        public virtual MealOption MealOption { get; set; }
        public virtual Member Member { get; set; }
    }
}
