//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XxxFitnessCLub.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DietDetail
    {
        public int ID { get; set; }
        public int DietLogID { get; set; }
        public double Portion { get; set; }
        public int MealOptionID { get; set; }
    
        public virtual DietLog DietLog { get; set; }
        public virtual MealOption MealOption { get; set; }
    }
}
